# -*- coding: utf-8 -*-
"""send_welcome.ipy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fGhBWXTPKjKzDuL8VoWMaz70_JJxoMNB
"""

import requests
import csv

API_KEY = "YOUR_API_KEY_HERE"
URL = "https://api.brevo.com/v3/smtp/email"

def send_email(email, prenom):
    payload = {
        "sender": {"email": "hello@startup.com", "name": "Startup"},
        "to": [{"email": email}],
        "subject": f"Bienvenue {prenom} 🎉",
        "htmlContent": f"""
        <h1>Bienvenue {prenom} !</h1>
        <p>Merci de vous être inscrit(e). Nous sommes heureux de vous compter parmi nous.</p>
        """
    }

    headers = {
        "api-key": API_KEY,
        "Content-Type": "application/json"
    }

    response = requests.post(URL, headers=headers, json=payload)
    return response.status_code, response.text



with open("inscrits.csv", encoding="utf-8") as f:
    for row in csv.DictReader(f):
        email = row["email"]
        prenom = row["prenom"]

        code, message = send_email(email, prenom)
        print(f"Email envoyé à {prenom} ({email}) → Status {code}")
        print(message)

